import { NextRequest, NextResponse } from "next/server";
import { validateSession } from "@/lib/server/session";
import { db } from "@/lib/server/db";

export const dynamic = "force-dynamic";
import { logAuditEvent } from "@/lib/server/audit";
import { createJaneChartNote } from "@/lib/server/jane-client";

function getClientIp(req: NextRequest): string {
  return (
    req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
    req.headers.get("x-real-ip") ??
    "unknown"
  );
}

// Build a human-readable chart note from the assessment result
function buildChartNoteContent(params: {
  totalScore: number;
  deq5Score: number;
  deq5Positive: boolean;
  severity: string;
  hasAutoimmune: boolean;
  hasDiabetes: boolean;
  hasMgd: boolean;
  triedTreatments: boolean;
  date: string;
}): string {
  const riskFactors: string[] = [];
  if (params.hasAutoimmune) riskFactors.push("Autoimmune condition (Sjogren's/RA/lupus)");
  if (params.hasDiabetes) riskFactors.push("Diabetes");
  if (params.hasMgd) riskFactors.push("Meibomian Gland Dysfunction (MGD) indicators");
  if (params.triedTreatments) riskFactors.push("Prior treatments attempted without full relief");

  const severityUpper = params.severity.toUpperCase();
  const deq5Status = params.deq5Positive
    ? `POSITIVE (score ≥ 6 — consistent with dry eye diagnosis per DEWS II)`
    : `NEGATIVE (score < 6)`;

  return [
    `KlaraMD Dry Eye Assessment`,
    `Date: ${params.date}`,
    ``,
    `Scores`,
    `  Total Score:  ${params.totalScore} / 36`,
    `  DEQ-5 Score:  ${params.deq5Score} / 18 — ${deq5Status}`,
    `  Severity:     ${severityUpper}`,
    ``,
    `Risk Factors`,
    riskFactors.length > 0
      ? riskFactors.map((f) => `  - ${f}`).join("\n")
      : `  None identified`,
    ``,
    `Screening`,
    `  No red flags detected. Patient appropriate for virtual care pathway.`,
    ``,
    `─────────────────────────────────────────────────`,
    `Generated by KlaraMD clinical decision support.`,
    `Results based on TFOS DEWS II/III guidelines.`,
    `To be reviewed and confirmed by treating ophthalmologist.`,
  ].join("\n");
}

// GET /api/assessments — returns current patient's assessment history
export async function GET(req: NextRequest) {
  const session = await validateSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: results, error } = await db
    .from("assessment_results")
    .select(
      "id, total_score, deq5_score, deq5_positive, severity, has_autoimmune, has_diabetes, has_mgd, tried_treatments, created_at"
    )
    .eq("patient_id", session.patientId)
    .order("created_at", { ascending: false });

  if (error) {
    return NextResponse.json({ error: "Failed to fetch assessments" }, { status: 500 });
  }

  await logAuditEvent(
    "patient",
    session.patientId,
    "list_assessments",
    "assessment_results",
    null,
    getClientIp(req)
  );

  // Reshape to match the AssessmentResult interface used by the client
  const history = (results ?? []).map((r) => ({
    id: r.id,
    timestamp: r.created_at,
    score: r.total_score,
    deq5: r.deq5_score,
    deq5Positive: r.deq5_positive,
    severity: r.severity,
    autoimmune: r.has_autoimmune,
    diabetes: r.has_diabetes,
    mgd: r.has_mgd,
    triedTreatments: r.tried_treatments,
  }));

  return NextResponse.json({ history });
}

// POST /api/assessments — persist a new assessment result and push to Jane
export async function POST(req: NextRequest) {
  const session = await validateSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await req.json();
    const {
      score,
      deq5,
      deq5Positive,
      severity,
      autoimmune,
      diabetes,
      mgd,
      triedTreatments,
      rawAnswers,
    } = body;

    if (score === undefined || deq5 === undefined || !severity) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const { data: result, error: insertError } = await db
      .from("assessment_results")
      .insert({
        patient_id: session.patientId,
        total_score: score,
        deq5_score: deq5,
        deq5_positive: deq5Positive ?? false,
        severity,
        has_autoimmune: autoimmune ?? false,
        has_diabetes: diabetes ?? false,
        has_mgd: mgd ?? false,
        tried_treatments: triedTreatments ?? false,
        raw_answers: rawAnswers ?? null,
      })
      .select("id, created_at")
      .single();

    if (insertError || !result) {
      console.error("[assessments] Insert error:", insertError);
      return NextResponse.json({ error: "Failed to save assessment" }, { status: 500 });
    }

    await logAuditEvent(
      "patient",
      session.patientId,
      "create_assessment",
      "assessment_results",
      result.id,
      getClientIp(req)
    );

    // ── Push to Jane as chart note (no-op if Jane not configured) ──────────
    try {
      const { data: patient } = await db
        .from("patients")
        .select("jane_patient_id")
        .eq("id", session.patientId)
        .single();

      if (patient?.jane_patient_id) {
        const date = result.created_at.split("T")[0];
        const content = buildChartNoteContent({
          totalScore: score,
          deq5Score: deq5,
          deq5Positive: deq5Positive ?? false,
          severity,
          hasAutoimmune: autoimmune ?? false,
          hasDiabetes: diabetes ?? false,
          hasMgd: mgd ?? false,
          triedTreatments: triedTreatments ?? false,
          date,
        });

        const janeNoteId = await createJaneChartNote({
          janePatientId: patient.jane_patient_id,
          content,
          date,
        });

        if (janeNoteId) {
          await db
            .from("assessment_results")
            .update({ jane_chart_note_id: janeNoteId })
            .eq("id", result.id);
        }
      }
    } catch (janeError) {
      console.error("[assessments] Jane chart note sync failed:", janeError);
    }

    return NextResponse.json({
      assessment: {
        id: result.id,
        timestamp: result.created_at,
      },
    });
  } catch (err) {
    console.error("[assessments] Unexpected error:", err);
    return NextResponse.json({ error: "An unexpected error occurred" }, { status: 500 });
  }
}
